
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsdb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
