security:
  oauth2:
    client:
      client-id: web
      client-secret: webpass
      user-authorization-uri: http://localhost:8081/oauth/authorize
      access-token-uri: http://localhost:8081/oauth/token
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
server:
  port: 8084
  servlet:
    session:
      cookie:
        name: CH

