server:
<<<<<<< HEAD
  port: 8083
=======
  port: 9191
>>>>>>> f3dadcfe1b5d2c1ca5ed104e667a4e853c2e4cc4
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauthDB?createDatabaseIfNotExist=true
    username: root
<<<<<<< HEAD
    password:
=======
    password: 1qazxsw2#
>>>>>>> f3dadcfe1b5d2c1ca5ed104e667a4e853c2e4cc4
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace